spring.application.name=api-gateway

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# USER SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# RESUME SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=resume-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://RESUME-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/resume/**

# AI SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=ai-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://AI-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/ai/**